### ISSUE TITLE
ERROR:root:Failed to download: https://w3id.org/biopragmatics/resources/rhea/rhea.json

### ISSUE THREAD

**Issue by sayalaruano** [Knowledge-Graph-Hub/kg-microbe#144]
Hi! I'm trying to create KG-microbe on my local computer, but when I try to download the resources needed got this error:

ERROR:root:Failed to download: https://w3id.org/biopragmatics/resources/rhea/rhea.json
Downloading files:  81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                       | 17/21 [00:00<00:00, 25.02it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sayalaruano/.cache/pypoetry/virtualenvs/kg-microbe-yG4npcK6-py3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sayalaruano/.cache/pypoetry/virtualenvs/kg-microbe-yG4npcK6-py3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/sayalaruano/.cache/pypoetry/virtualenvs/kg-microbe-yG4npcK6-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sayalaruano/.cache/pypoetry/virtualenvs/kg-microbe-yG4npcK6-py3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sayalaruano/.cache/pypoetry/virtualenvs/kg-microbe-yG4npcK6-py3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/sayalaruano/Windows-SSD/Users/sayalaruano/OneDrive - Universidad San Francisco de Quito/Documentos/School/Maastricht/Thesis/MicWasteWatKG/Extra_metadata/kg-microbe-master/kg_microbe/run.py", line 53, in download
    kg_download(*args, **kwargs)
  File "/run/media/sayalaruano/Windows-SSD/Users/sayalaruano/OneDrive - Universidad San Francisco de Quito/Documentos/School/Maastricht/Thesis/MicWasteWatKG/Extra_metadata/kg-microbe-master/kg_microbe/download.py", line 22, in download
    download_from_yaml(
  File "/home/sayalaruano/.cache/pypoetry/virtualenvs/kg-microbe-yG4npcK6-py3.11/lib/python3.11/site-packages/kghub_downloader/download_utils.py", line 134, in download_from_yaml
    with urlopen(req) as response, open(outfile, "wb") as out_file:  # type: ignore
         ^^^^^^^^^^^^
  File "/home/sayalaruano/.pyenv/versions/3.11.8/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sayalaruano/.pyenv/versions/3.11.8/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/sayalaruano/.pyenv/versions/3.11.8/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/home/sayalaruano/.pyenv/versions/3.11.8/lib/python3.11/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sayalaruano/.pyenv/versions/3.11.8/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/home/sayalaruano/.pyenv/versions/3.11.8/lib/python3.11/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sayalaruano/.pyenv/versions/3.11.8/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/sayalaruano/.pyenv/versions/3.11.8/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/home/sayalaruano/.pyenv/versions/3.11.8/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sayalaruano/.pyenv/versions/3.11.8/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/home/sayalaruano/.pyenv/versions/3.11.8/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

Is there something wrong with this link/resource? How can I solve it?

Thanks in advance for your help.

**Comment by hrshdhgd** [comment]
Hi @sayalaruano ! Yes, the resource got changed to a gzip file. Try to get the latest version of the `master` branch and rerun. It was fixed just yesterday.

**Comment by sayalaruano** [comment]
It is working now. Thanks!
