### ISSUE TITLE
Repair build errors due to ModuleNotFoundError of numpy

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-microbe#46]
The graph currently fails to build on Jenkins (see error below).
```
08:23:38  Collecting pandas (from kg-microbe==1.0.0)
08:23:38    Using cached https://files.pythonhosted.org/packages/99/f0/f99700ef327e51d291efdf4a6de29e685c4d198cbf8531541fc84d169e0e/pandas-1.3.5.tar.gz
08:23:39      Complete output from command python setup.py egg_info:
08:23:39      Traceback (most recent call last):
08:23:39        File "<string>", line 1, in <module>
08:23:39        File "/tmp/pip-build-2_cqjoc1/pandas/setup.py", line 18, in <module>
08:23:39          import numpy
08:23:39      ModuleNotFoundError: No module named 'numpy'
08:23:39      
08:23:39      ----------------------------------------
08:23:39  Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2_cqjoc1/pandas/
```

A full refresh of the Jenkins build may require a new Docker image, as currently used for KG-IDG or KG-COVID-19.

**Comment by caufieldjh** [comment]
Resolved by #47
